### ISSUE TITLE
Hover will also be triggered when the label's "real" position is passed

### ISSUE THREAD

**Issue by stevenobird** [kapantzak/barIndicator#16]
Like the title says, when I take a label with a bigger size - for example with an image - the hover event won't be only triggered when I pass the mlHoverRange in the bar; the hover event also starts when I pass the "real" position of the image/milestone label.

I can't even hack myself into this with z-indexes.

**Comment by kapantzak** [comment]
Issue solved (added some css rules and some event handlers)
